### ISSUE TITLE
Permissions with Elastic, Mongo, and Redis

### ISSUE THREAD

**Issue by SpontaneousDuck** [allegroai/trains-server-k8s#18]
It seems the permissions when using NFS storage for these services (Elastic, Mongo, and Redis) has a lot of issues. All three containers start as root and try to `chown` their data directories to the required uid as root. Since these directories are mounted over NFS, this has varying degrees of success since NFS remaps UIDs for security reasons. Most of the issues I have seen in the respective container's repos say that you should mount as the correct user and make sure the permissions are correct. To do this with clearml, I had to make sure the UIDs for the folder matched what I listed below. I also made the changes for each containers spec.

- Elasticsearch: UID 1000
  - Remove the InitContainer section of `eleasticsearch-deployment.yaml`
- Redis: UID 999
- MongoDB: UID 999
  - Add the below to `mongo-deployment.yaml` in the container spec. This will bypass the chown and just run the database
  - ```
    securityContext:
          runAsUser: 999
    ```

I don't know if there is a better way to solve this.. Does anyone have any ideas?

**Comment by jkhenning** [comment]
Hi @SpontaneousDuck,

Starting with the new Helm chart we're working on, these will be handled by public ES, Mongo and Redis charts (where a PVC is used), so I assume the question will be moot by then 😉 

Meanwhile, if it works, I say keep using it until we update the chart

**Comment by SpontaneousDuck** [comment]
Great! Glad those are being worked on. I will leave this here for reference for anyone having the same problems!

**Comment by lukemarsden** [comment]
Hi @jkhenning where can we follow along the progress of the new helm chart please? Is there a draft WIP we can see somewhere? We are starting work on deploying ClearML on Kubernetes and we'd like to see the best way to do this. Thanks!

**Comment by sapir-allegro** [comment]
Hey @lukemarsden,
The current progress isn't published yet. But in the meanwhile you can take a look at @valeriano-manassero's charts.
We will be using his contribution in our new helm charts.
You can find his charts here:
https://artifacthub.io/packages/helm/valeriano-manassero/clearml
