### ISSUE TITLE
Helm dependencies usage

### ISSUE THREAD

**Issue by ghost** [allegroai/trains-server-k8s#9]
Hi,
I see in the Helm chart some dependencies like:
Elasticsearch
MongoDB
Redis

There is a specific reason why Helm dependencies pointing to official charts are not used?
Reference here: https://helm.sh/docs/helm/helm_dependency/

Thank you.

**Comment by jkhenning** [comment]
Hi @valeriano-manassero ,

That sounds like a very good idea, however the main issue is whether can we make sure these official charts will only expose their respective service (i.e. Redis, MongoDB and Elastic) to the Trains Server components, and will not be accessible externally...

What do you think?

**Comment by ghost** [comment]
> Hi @valeriano-manassero ,
> 
> That sounds like a very good idea, however the main issue is whether can we make sure these official charts will only expose their respective service (i.e. Redis, MongoDB and Elastic) to the Trains Server components, and will not be accessible externally...
> 
> What do you think?

I agree, this is possible disabling any ingress in the linked charts and using ClusterIP. Will issue a WIP PR asap.

**Comment by ghost** [comment]
Issued a first WIP proposal here https://github.com/allegroai/trains-server-k8s/pull/12

**Comment by ghost** [comment]
I'd say we can eventually discuss on the PR itself now that should be completed.
